name: Deploy SkillSwap Backend

on:
  push:
    branches: [ master, main ]
    paths:
      - 'SkillSwapBE/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'SkillSwapBE/**'

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Test backend
      run: |
        cd SkillSwapBE
        go mod tidy
        go test ./...
        
    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        # Create a temporary directory for deployment
        mkdir -p /tmp/heroku-deploy
        
        # Copy SkillSwapBE contents to temp directory
        cp -r SkillSwapBE/* /tmp/heroku-deploy/
        
        # Initialize git repo in temp directory
        cd /tmp/heroku-deploy
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b main
        
        # Add and commit all files
        git add .
        git commit -m "Deploy backend to Heroku"
        
        # Add Heroku remote and push
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku main --force