name: Deploy SkillSwap Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'SkillSwapWeb/**'
      - '.github/workflows/deploy-web.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build and Deploy to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SkillSwapWeb
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './SkillSwapWeb/package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create environment file
      run: |
        echo "VITE_AUTH0_DOMAIN=foxcroft.uk.auth0.com" > .env
        echo "VITE_AUTH0_CLIENT_ID=bxb3lnEpfomkMeaDLw63mH37EZZgKJtW" >> .env
        echo "VITE_API_BASE_URL=https://skillswapbe.herokuapp.com/api/v1" >> .env
        
    - name: Build application
      run: npm run build
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './SkillSwapWeb/dist'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4